import{a as v,S as h,i as c}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const w="44262674-4191f931eb8b9eeb7747e3c1c";async function g(t,r=1){return(await v("https://pixabay.com/api/",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".div-loader");f.style.display="none";let l=new h(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});function y(t){const r=t.map(({largeImageURL:s,tags:n,webformatURL:e,likes:o,views:a,comments:E,downloads:S})=>`
              <a href="${s}" class="gallery-item">
                <img src="${e}" alt="${n}" loading="lazy">
                <div class="info">
                  <p><b>Likes:</b> ${o}</p>
                  <p><b>Views:</b> ${a}</p>
                  <p><b>Comments:</b> ${E}</p>
                  <p><b>Downloads:</b> ${S}</p>
                </div>
              </a>
          `).join("");m.insertAdjacentHTML("beforeend",r),l?l.refresh():(l=new h(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",scrollZoom:!1}),l.on("error.simplelightbox",function(s){console.log(s)}))}function b(){f.style.display="block"}function d(){f.style.display="none"}const P=document.querySelector(".form"),i=document.querySelector(".load-more");let u="",p=1;i.addEventListener("click",$);P.addEventListener("submit",t=>{if(t.preventDefault(),u=t.target.elements.searchQuery.value.trim(),i.classList.add("hidden"),!u.length){c.error({title:"Error",message:'"Sorry, input is empty"',position:"topRight"}),i.classList.add("hidden");return}p=1,m.innerHTML="",b(),g(u).then(r=>{if(!r.hits.length){c.error({title:"Error",message:'"Sorry, there are no images matching your search query. Please try again!"',position:"topRight"}),i.classList.add("hidden"),d();return}i.classList.remove("hidden"),L(r),y(r.hits),l.refresh(),d()}).catch(r=>{c.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error("Error fetching pictures:",r),d()})});async function $(){p++,i.disabled=!0,i.classList.add("hidden"),b();try{const t=await g(u,p);L(t),y(t.hits),q()}catch(t){console.log(t)}finally{i.disabled=!1,d(),i.classList.remove("hidden")}}function L(t){p>=Math.ceil(t.totalHits/15)&&(i.classList.add("hidden"),c.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}))}function q(){let t=document.querySelector(".gallery-item"),r=t.getBoundingClientRect();console.log(r),t&&window.scrollBy({top:r.height+300,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
